### PR TITLE
Use MSVC over WIN32 for selecting compiler options

### PR DESCRIPTION
**Pull request by OttoHatt**
Allows using GCC & Clang on Windows.

### CODE REVIEW

**Comment by OttoHatt** [comment]
Treating warnings as errors means Nicegraf doesn't compile under GCC w/ Mingw64; but this is more correct.

**Comment by nicebyte** [comment]
i don't mind taking this specific pr, but note that the only compiler supported by nicegraf on windows is msvc. we don't build or test with anything other than msvc on windows. we may also use msvc-specific extensions on windows  (don't think it's  the  case right now, but we "reserve the right", so to speak).

**Comment by nicebyte** [comment]
please rebase your branch on the repo's master so that the CI checks may run.

**Comment by OttoHatt** [comment]
Couldn't rebase on the web client (hope squashing the commits is acceptable)

**Pull request merged**
